project:
  type: website
  output-dir: ../public/blog

website:
  title: "Karim's Blog"
  navbar: false
  sidebar: false
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    date-format: "D/M/YYYY"
    comments:
      giscus:
        repo: kanayai/karim_ai_website
        mapping: title
        theme: auto
